# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example
  pod 'SnapSDK', :subspecs => ['SCSDKCreativeKit']

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
